name: PlatformIO CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  changes:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - id: filter
        uses: dorny/paths-filter@v2
        with:
          filters: |
            src:
              - 'platformio.ini'
              - 'src/**'
              - 'include/**'

    outputs:
      src: ${{ steps.filter.outputs.src }}

  build:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install PlatformIO Core
        run: pip install --upgrade platformio
      - name: Run PlatformIO
        run: pio run

  format:
    runs-on: ubuntu-latest
    needs: changes
    if: ${{ needs.changes.outputs.src == 'true' }}

    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Check clang-format
        uses: DoozyX/clang-format-lint-action@v0.14
        with:
          source: "./src ./include"
          extensions: "h,hpp,c,cpp"
          clangFormatVersion: 11
          style: file
          inplace: false
